"""
skill_effects_generated.py - 自动生成，请勿手动编辑。

由 scripts/generate_skill_effects.py 从数据库 description 批量生成。
"""

from src.effect_models import E, EffectTag
from src.effect_data import T, on_attack, on_status, on_defense

SKILL_EFFECTS_GENERATED = {
    "一拳": [T(E.DAMAGE)],
    "三连破": [T(E.SELF_BUFF, atk=0.3)],
    "三鼓作气": [T(E.SELF_BUFF, atk=0.3)],
    "不动如山": [T(E.DAMAGE_REDUCTION, pct=0.9)],
    "不可接触": [
        T(E.DAMAGE_REDUCTION, pct=0.5),
        T(E.POISON, stacks=1),
    ],
    "丢冰块": [
        T(E.DAMAGE),
        T(E.SELF_BUFF, speed=-0.3),
    ],
    "主场优势": [],
    "主轴": [T(E.DAMAGE)],
    "乘胜追击": [T(E.DAMAGE)],
    "乘风": [T(E.SELF_BUFF, speed=1.2)],
    "乱打": [T(E.DAMAGE)],
    "二律背反": [T(E.METEOR, stacks=3)],
    "交叉闪电": [T(E.DAMAGE)],
    "仙人掌刺击": [T(E.DAMAGE)],
    "以重制重": [],
    "休息回复": [T(E.HEAL_HP, pct=0.3)],
    "传感器": [T(E.DAMAGE)],
    "伪造账单": [],
    "伺机而动": [T(E.NEXT_ATTACK_MOD, power_bonus=70)],
    "俯冲猛击": [T(E.DAMAGE)],
    "借用": [],
    "假寐": [T(E.HEAL_ENERGY, amount=2)],
    "偷师": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "充分燃烧": [],
    "先发制人": [T(E.DAMAGE)],
    "光之矛": [T(E.DAMAGE)],
    "光刃": [T(E.DAMAGE)],
    "光合作用": [],
    "光球": [T(E.DAMAGE)],
    "光能聚集": [T(E.DAMAGE)],
    "冥想": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.METEOR, stacks=2),
    ],
    "冬至": [T(E.WEATHER, type="snow", turns=8)],
    "冰冻光线": [
        T(E.DAMAGE),
        T(E.ENEMY_ENERGY_COST_UP, amount=2),
    ],
    "冰刺": [T(E.DAMAGE)],
    "冰墙": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.FREEZE, stacks=2),
    ],
    "冰天雪地": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.ENEMY_ENERGY_COST_UP, amount=3),
    ],
    "冰捆缚": [T(E.ENEMY_ENERGY_COST_UP, amount=1)],
    "冰晶坠": [
        T(E.DAMAGE),
        T(E.ENEMY_ENERGY_COST_UP, amount=1),
    ],
    "冰点": [T(E.FREEZE, stacks=5)],
    "冰爪": [T(E.DAMAGE)],
    "冰荆棘": [T(E.DAMAGE_REDUCTION, pct=0.7)],
    "冰蛋壳": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "冰锋横扫": [],
    "冰锥": [T(E.DAMAGE)],
    "冰雹": [
        T(E.DAMAGE),
        T(E.ENEMY_ENERGY_COST_UP, amount=3),
    ],
    "冲击": [T(E.DAMAGE)],
    "冲撞": [T(E.DAMAGE)],
    "冷风": [T(E.DAMAGE)],
    "击鼓传花": [T(E.FORCE_SWITCH)],
    "刺盾": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.ENEMY_DEBUFF, atk=0.5),
    ],
    "刺藤": [T(E.DAMAGE)],
    "剧毒": [T(E.POISON, stacks=3)],
    "力量吞噬": [
        T(E.SKILL_MOD, target='self', stat='power', value=20),
        T(E.SKILL_MOD, target='enemy', stat='power', value=-20),
    ],
    "加固": [T(E.SELF_BUFF, {"def": 1.4})],
    "加大功率": [
        T(E.HEAL_ENERGY, amount=8),
        T(E.FORCE_SWITCH),
    ],
    "勾魂": [T(E.STEAL_ENERGY, amount=3)],
    "化劲": [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.4)],
    "升龙咆哮": [T(E.DAMAGE)],
    "午夜噪音": [T(E.DAMAGE)],
    "压扁": [T(E.DAMAGE)],
    "双响炮": [T(E.DAMAGE)],
    "双联脉冲": [T(E.DAMAGE)],
    "反击拳": [T(E.DAMAGE)],
    "反弹": [],
    "取念": [],
    "叠势": [T(E.DAMAGE)],
    "叶绿光束": [T(E.DAMAGE)],
    "后发制人": [T(E.DAMAGE)],
    "吞噬": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=6),
    ],
    "吨位压制": [],
    "吹火": [T(E.DAMAGE)],
    "吹炎": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "咆哮": [T(E.ENEMY_DEBUFF, atk=1.3)],
    "啃咬": [T(E.DAMAGE)],
    "啄击": [T(E.DAMAGE)],
    "嗜痛": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.SELF_BUFF, atk=0.2, spatk=0.2),
    ],
    "噬心": [T(E.DAMAGE)],
    "四维降解": [T(E.DAMAGE)],
    "回旋风暴": [T(E.DAMAGE)],
    "地陷": [
        T(E.DAMAGE),
        T(E.SELF_BUFF, {"def": 0.6}),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "地震": [T(E.DAMAGE)],
    "坍缩": [
        T(E.DAMAGE),
        T(E.SELF_BUFF, spatk=0.5),
    ],
    "坟场搏击": [T(E.DAMAGE)],
    "垂死反击": [T(E.DAMAGE)],
    "埋伏": [T(E.DAMAGE)],
    "堆雪人": [T(E.DAMAGE)],
    "增程电池": [],
    "壁垒": [T(E.DAMAGE_REDUCTION, pct=0.9)],
    "复写": [],
    "多维击打": [
        T(E.DAMAGE),
        T(E.METEOR, stacks=1),
    ],
    "大爆炸": [T(E.DAMAGE)],
    "天光": [T(E.DAMAGE)],
    "天旋地转": [T(E.DAMAGE)],
    "天火": [T(E.BURN, stacks=10)],
    "孢子": [T(E.LEECH, stacks=1)],
    "孢子爆散": [T(E.DAMAGE)],
    "寄生种子": [],
    "富养化": [T(E.HEAL_ENERGY, amount=3)],
    "寒风吹": [
        T(E.DAMAGE),
        T(E.ENEMY_DEBUFF, spdef=0.4),
    ],
    "寸拳": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "导电撞击": [T(E.DAMAGE)],
    "小偷小摸": [T(E.STEAL_ENERGY, amount=3)],
    "尾后针": [T(E.DAMAGE)],
    "山火": [T(E.DAMAGE)],
    "岩土暴击": [T(E.DAMAGE)],
    "岩脉崩毁": [T(E.DAMAGE)],
    "幻象": [T(E.DAMAGE)],
    "幼态延续": [T(E.DAMAGE)],
    "幽灵爆发": [T(E.DAMAGE)],
    "应激反应": [T(E.HEAL_HP, pct=0.25)],
    "引雷": [T(E.DAMAGE)],
    "强制重启": [T(E.DAMAGE)],
    "当头棒喝": [T(E.DAMAGE)],
    "彗星": [T(E.DAMAGE)],
    "影袭": [T(E.DAMAGE)],
    "彼岸之手": [T(E.DAMAGE)],
    "徒长": [T(E.HEAL_ENERGY, amount=10)],
    "心灵洞悉": [T(E.METEOR, stacks=1)],
    "快速移动": [T(E.SELF_BUFF, speed=0.7)],
    "念力膨胀": [T(E.DAMAGE)],
    "怒火": [T(E.SELF_BUFF, atk=1.3, spatk=1.3)],
    "怨力打击": [T(E.DAMAGE)],
    "恐吓": [T(E.DAMAGE)],
    "恶作剧": [T(E.ENEMY_LOSE_ENERGY, amount=3)],
    "恶念交换": [],
    "恶能量": [T(E.DAMAGE)],
    "惊吓盒子": [
        T(E.DAMAGE),
        T(E.ENEMY_LOSE_ENERGY, amount=6),
    ],
    "感电": [T(E.DAMAGE)],
    "截拳": [T(E.DAMAGE)],
    "打雪仗": [T(E.DAMAGE)],
    "打鼾": [T(E.DAMAGE)],
    "扫尾": [T(E.DAMAGE)],
    "扬沙": [T(E.DAMAGE)],
    "技巧打击": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=10.0)),
    ],
    "抓挠": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "折射": [
        T(E.DAMAGE),
        T(E.METEOR, stacks=1),
    ],
    "折线冲击": [T(E.DAMAGE)],
    "抛石": [T(E.DAMAGE)],
    "报复": [
        T(E.DAMAGE_REDUCTION, pct=0.6),
        T(E.ENEMY_LOSE_ENERGY, amount=3),
        on_attack(T(E.ENEMY_LOSE_ENERGY, amount=3)),
    ],
    "拆卸": [T(E.DAMAGE)],
    "拍击": [T(E.DAMAGE)],
    "持续高温": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "指指点点": [T(E.DAMAGE)],
    "捆缚": [T(E.POISON, stacks=2)],
    "捧杀": [T(E.DAMAGE_REDUCTION, pct=0.9)],
    "掠夺": [T(E.DAMAGE)],
    "掩护": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.FORCE_SWITCH),
    ],
    "提气": [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.4)],
    "摇篮曲": [T(E.ENEMY_ENERGY_COST_UP, amount=3)],
    "撒娇": [T(E.DAMAGE)],
    "撕咬": [T(E.DAMAGE)],
    "撕裂": [
        T(E.DAMAGE),
        T(E.LIFE_DRAIN, pct=1.0),
    ],
    "操控": [T(E.ENEMY_ENERGY_COST_UP, amount=7)],
    "攻击场地": [],
    "放晴": [],
    "散手": [T(E.DAMAGE)],
    "旋转突击": [T(E.DAMAGE)],
    "无影脚": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "无畏之心": [T(E.DAMAGE_REDUCTION, pct=1.0)],
    "易燃物质": [
        T(E.DAMAGE),
        T(E.BURN, stacks=2),
    ],
    "星云漩涡": [T(E.DAMAGE)],
    "星星撞击": [T(E.DAMAGE)],
    "星轨裂变": [T(E.METEOR, stacks=2)],
    "星链": [T(E.METEOR, stacks=1)],
    "晒太阳": [T(E.CLEANSE, target='enemy', mode='buffs')],
    "暗突袭": [
        T(E.DAMAGE),
        T(E.LIFE_DRAIN, pct=0.5),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "暗箱操作": [T(E.SELF_BUFF, {"def": -1.0}, atk=-1.0, spatk=-1.0, spdef=-1.0)],
    "暴风眼": [],
    "暴风雪": [
        T(E.DAMAGE),
        T(E.FREEZE, stacks=1),
    ],
    "月光合奏": [T(E.DAMAGE)],
    "有效预防": [T(E.DAMAGE_REDUCTION, pct=0.5)],
    "束缚": [T(E.POISON, stacks=2)],
    "杠杆置换": [T(E.HEAL_ENERGY, amount=2)],
    "极寒领域": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "极速冷冻": [T(E.ENEMY_ENERGY_COST_UP, amount=2)],
    "极限撕裂": [T(E.DAMAGE)],
    "架势": [T(E.HEAL_HP, pct=0.2)],
    "柔弱": [T(E.ENEMY_DEBUFF, {"def": 0.7}, atk=0.7)],
    "根吸收": [T(E.HEAL_HP, pct=0.15)],
    "栽赃": [T(E.DAMAGE)],
    "械斗": [T(E.DAMAGE)],
    "棘刺": [],
    "棘突": [T(E.DAMAGE)],
    "横纵斩": [T(E.DAMAGE)],
    "欺诈契约": [],
    "毒孢子": [T(E.POISON, stacks=5)],
    "毒沼": [T(E.DAMAGE)],
    "毒泡泡": [T(E.DAMAGE)],
    "毒针": [
        T(E.DAMAGE),
        T(E.POISON, stacks=1),
    ],
    "气势一击": [T(E.DAMAGE)],
    "气沉丹田": [
        T(E.SELF_BUFF, atk=1.3),
        T(E.HEAL_HP, pct=0.6),
    ],
    "气泡": [T(E.DAMAGE)],
    "气波": [T(E.DAMAGE)],
    "氧输送": [
        T(E.SELF_BUFF, spatk=0.8),
        T(E.HEAL_ENERGY, amount=4),
    ],
    "水光冲击": [T(E.DAMAGE)],
    "水幕冲击": [T(E.DAMAGE)],
    "水弹": [T(E.DAMAGE)],
    "水弹枪": [T(E.DAMAGE)],
    "水星水": [],
    "水泡盾": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.SELF_BUFF, spatk=0.4),
    ],
    "水波术": [T(E.DAMAGE)],
    "水炮": [T(E.DAMAGE)],
    "水花四溅": [T(E.DAMAGE)],
    "求雨": [T(E.WEATHER, type='rain', turns=8)],
    "沙涌": [T(E.WEATHER, type="sandstorm", turns=8)],
    "泡沫": [T(E.DAMAGE)],
    "泥巴喷射": [T(E.DAMAGE)],
    "泥沼": [],
    "泥浆": [T(E.DAMAGE)],
    "泥浆铠甲": [T(E.SELF_BUFF, {"def": 0.4}, atk=0.4)],
    "洗礼": [
        T(E.SKILL_MOD, target='self', stat='cost', value=-1),
        T(E.CLEANSE, target='self', mode='debuffs'),
    ],
    "流星火雨": [T(E.DAMAGE)],
    "流沙": [T(E.ENEMY_DEBUFF, all_def=0.6)],
    "流火": [T(E.DAMAGE)],
    "消毒法": [T(E.DAMAGE)],
    "涌泉": [T(E.DAMAGE)],
    "润泽": [T(E.SELF_BUFF, spatk=1.9)],
    "淤泥表皮": [T(E.DAMAGE_REDUCTION, pct=0.8)],
    "淬火": [T(E.DAMAGE_REDUCTION, pct=0.7)],
    "湮灭": [T(E.DAMAGE)],
    "湿润印记": [],
    "溃烂触碰": [T(E.DAMAGE)],
    "溶解液": [],
    "滚雪球": [
        T(E.DAMAGE),
        T(E.FREEZE, stacks=2),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "漫反射": [],
    "潮汐": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "潮涌": [T(E.DAMAGE)],
    "激怒": [T(E.ENEMY_ENERGY_COST_UP, amount=3)],
    "激流": [T(E.DAMAGE)],
    "火云车": [T(E.DAMAGE)],
    "火焰冲锋": [T(E.DAMAGE)],
    "火焰切割": [T(E.DAMAGE)],
    "火焰箭": [T(E.DAMAGE)],
    "火爪": [T(E.DAMAGE)],
    "火苗": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "灵光": [T(E.DAMAGE)],
    "灵媒": [T(E.DAMAGE)],
    "灼伤": [T(E.DAMAGE)],
    "灾厄": [T(E.DAMAGE)],
    "炎息": [T(E.DAMAGE)],
    "炎打": [T(E.DAMAGE)],
    "炎枪": [T(E.DAMAGE)],
    "炎爆术": [],
    "炙热波动": [
        T(E.DAMAGE),
        T(E.BURN, stacks=4),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "烈焰风暴": [
        T(E.DAMAGE),
        T(E.BURN, stacks=6),
    ],
    "热气": [T(E.DAMAGE)],
    "热砂": [T(E.DAMAGE)],
    "热身": [T(E.NEXT_ATTACK_MOD, power_pct=1.0)],
    "热身运动": [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)],
    "焚毁": [T(E.DAMAGE)],
    "焚烧烙印": [T(E.BURN, stacks=5)],
    "燃尽": [T(E.DAMAGE)],
    "爆冲": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=5.0)),
    ],
    "爆米花爆破": [T(E.DAMAGE)],
    "爆裂飞弹": [T(E.DAMAGE)],
    "牵连": [T(E.DAMAGE)],
    "猛烈撞击": [T(E.DAMAGE)],
    "玩具乐园": [T(E.SELF_BUFF, speed=0.2)],
    "球状闪电": [T(E.DAMAGE)],
    "甜心续航": [T(E.HEAL_HP, pct=0.4)],
    "生日蛋糕": [],
    "电弧": [T(E.DAMAGE)],
    "电流": [T(E.DAMAGE)],
    "电磁偏转": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "电离爆破": [T(E.SELF_BUFF, speed=-0.4)],
    "疾风刺": [T(E.DAMAGE)],
    "疾风涡轮": [T(E.DAMAGE)],
    "瘴气喷射": [T(E.DAMAGE)],
    "盛开": [
        T(E.SKILL_MOD, target='self', stat='power_pct', value=0.3),
        on_defense(T(E.SKILL_MOD, target='self', stat='power_pct', value=0.7)),
    ],
    "瞬间零度": [T(E.ENEMY_ENERGY_COST_UP, amount=3)],
    "石肤术": [T(E.SELF_BUFF, {"def": 1.6})],
    "石锁": [T(E.DAMAGE)],
    "砂糖弹球": [],
    "破绽": [
        T(E.SELF_BUFF, atk=0.5),
        T(E.ENEMY_DEBUFF, all_def=0.5),
        on_defense(T(E.SELF_BUFF, atk=0.5)),
    ],
    "破罐破摔": [T(E.DAMAGE)],
    "破防": [T(E.ENEMY_DEBUFF, all_def=1.3)],
    "硬化": [T(E.DAMAGE_REDUCTION, pct=0.9)],
    "硬门": [on_attack(T(E.INTERRUPT))],
    "碎冰冰": [
        T(E.DAMAGE),
        T(E.FREEZE, stacks=1),
    ],
    "碎冰击": [
        T(E.DAMAGE),
        T(E.ENEMY_ENERGY_COST_UP, amount=1),
    ],
    "碰爪": [T(E.DAMAGE)],
    "磁干扰": [T(E.DAMAGE)],
    "磁暴": [T(E.DAMAGE)],
    "示弱": [],
    "离子火花": [T(E.DAMAGE)],
    "离子震荡": [T(E.DAMAGE)],
    "种子弹": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "种皮爆裂": [T(E.DAMAGE)],
    "移花接木": [
        T(E.HEAL_HP, pct=0.15),
        T(E.FORCE_SWITCH),
    ],
    "空间压迫": [
        T(E.DAMAGE),
        T(E.METEOR, stacks=1),
    ],
    "穿膛": [T(E.DAMAGE)],
    "突袭": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=3.0)),
    ],
    "等价交换": [T(E.DAMAGE_REDUCTION, pct=0.9)],
    "筛管奔流": [T(E.DAMAGE)],
    "粒子对撞": [T(E.DAMAGE)],
    "精神扰乱": [T(E.ENEMY_ENERGY_COST_UP, amount=1)],
    "纤维化": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.SELF_BUFF, {"def": 0.4}),
    ],
    "绵里藏针": [T(E.DAMAGE)],
    "缓冻": [T(E.DAMAGE)],
    "缠丝劲": [T(E.DAMAGE)],
    "网缚": [
        T(E.DAMAGE),
        T(E.ENEMY_DEBUFF, {"def": 0.3}),
    ],
    "羽刃": [
        T(E.DAMAGE),
        T(E.FORCE_SWITCH),
    ],
    "羽化加速": [T(E.AGILITY)],
    "羽毛舞": [T(E.AGILITY)],
    "羽翼庇护": [T(E.DAMAGE_REDUCTION, pct=0.7)],
    "翅刃": [T(E.DAMAGE)],
    "翼击": [
        T(E.AGILITY),
        T(E.DAMAGE),
    ],
    "耀眼": [T(E.SKILL_MOD, target='enemy', stat='hit_count', value=-4)],
    "聒噪": [T(E.ENEMY_ENERGY_COST_UP, amount=3)],
    "联动装置": [],
    "聚盐": [T(E.HEAL_HP, pct=0.05)],
    "肥皂泡": [T(E.DAMAGE)],
    "背袭": [T(E.DAMAGE)],
    "能量守恒": [T(E.DAMAGE_REDUCTION, pct=0.8)],
    "能量炮": [T(E.DAMAGE)],
    "脉冲光线": [T(E.DAMAGE)],
    "腐化": [
        T(E.ENEMY_DEBUFF, all_atk=0.3),
        T(E.POISON, stacks=1),
    ],
    "腐蚀酸液": [
        T(E.DAMAGE),
        T(E.POISON, stacks=2),
    ],
    "花炮": [T(E.SELF_BUFF, spatk=0.5)],
    "花香": [T(E.DAMAGE)],
    "芳香诱引": [
        T(E.SKILL_MOD, target='self', stat='hit_count', value=3),
        on_defense(T(E.INTERRUPT)),
    ],
    "荆棘爪": [T(E.DAMAGE)],
    "荟萃": [],
    "落井下毒": [],
    "落星": [T(E.DAMAGE)],
    "落石": [T(E.DAMAGE)],
    "落雨": [T(E.WEATHER, type="rain", turns=8)],
    "落雷": [T(E.DAMAGE)],
    "蓄势待发": [],
    "蓄水": [],
    "蓄能轰击": [T(E.DAMAGE)],
    "藤绞": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=5),
    ],
    "藤鞭": [T(E.DAMAGE)],
    "虚假破产": [T(E.DAMAGE_REDUCTION, pct=0.8)],
    "虚化": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.SELF_BUFF, spdef=0.4),
    ],
    "虫击": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "虫刺": [T(E.DAMAGE)],
    "虫结阵": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "虫网": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "虫群": [T(E.DAMAGE)],
    "虫群智慧": [],
    "虫群过境": [T(E.DAMAGE)],
    "虫茧": [T(E.HEAL_HP, pct=0.2)],
    "虫蛊": [T(E.DAMAGE)],
    "虫鸣": [T(E.DAMAGE)],
    "虹光冲击": [T(E.DAMAGE)],
    "蛰针": [T(E.DAMAGE)],
    "蜡质膜": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.HEAL_ENERGY, amount=3),
    ],
    "血气": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "裂石": [
        T(E.DAMAGE),
        T(E.ENEMY_DEBUFF, {"def": 0.8}),
    ],
    "见招拆招": [T(E.DAMAGE)],
    "角击": [T(E.DAMAGE)],
    "触底强击": [T(E.DAMAGE)],
    "触电": [T(E.DAMAGE)],
    "许愿星": [T(E.DAMAGE)],
    "诋毁": [T(E.DAMAGE)],
    "诡刺": [T(E.DAMAGE)],
    "贪婪": [T(E.GRANT_LIFE_DRAIN, pct=1.0)],
    "贮藏": [T(E.SELF_BUFF, atk=0.5, spatk=0.5)],
    "贯手": [T(E.DAMAGE)],
    "赤子之心": [T(E.HEAL_HP, pct=0.4)],
    "趁火打劫": [T(E.DAMAGE)],
    "超导": [T(E.DAMAGE)],
    "超导加速": [
        T(E.DAMAGE),
        T(E.SELF_BUFF, speed=0.3),
    ],
    "超新星馈赠": [T(E.METEOR, stacks=2)],
    "超级糖果": [T(E.DAMAGE)],
    "超维投射": [T(E.METEOR, stacks=4)],
    "跌落": [
        T(E.DAMAGE),
        T(E.SELF_BUFF, atk=0.5),
    ],
    "践踏": [T(E.DAMAGE)],
    "跺地": [T(E.DAMAGE)],
    "过曝": [T(E.DAMAGE)],
    "过载回路": [T(E.FORCE_SWITCH)],
    "远程访问": [T(E.FORCE_ENEMY_SWITCH)],
    "连续毒针": [
        T(E.DAMAGE),
        T(E.POISON, stacks=1),
    ],
    "连续爪击": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)),
    ],
    "迫害": [T(E.DAMAGE)],
    "迫近攻击": [T(E.DAMAGE)],
    "追打": [T(E.DAMAGE)],
    "退化": [],
    "逆向演化": [],
    "逆袭": [T(E.DAMAGE)],
    "透射": [T(E.DAMAGE)],
    "速冻": [],
    "遁地": [
        T(E.DAMAGE_REDUCTION, pct=0.5),
        T(E.FORCE_SWITCH),
    ],
    "酶浓度调整": [
        T(E.DAMAGE_REDUCTION, pct=0.7),
        T(E.HEAL_HP, pct=0.2),
    ],
    "重击": [T(E.DAMAGE)],
    "金属噪音": [T(E.DAMAGE)],
    "针状物": [T(E.DAMAGE)],
    "钢钻": [],
    "钢铁洪流": [T(E.DAMAGE)],
    "钧势": [T(E.SELF_BUFF, {"def": 1.4})],
    "错乱": [
        T(E.DAMAGE),
        T(E.METEOR, stacks=3),
    ],
    "镜像反射": [T(E.DAMAGE_REDUCTION, pct=0.8)],
    "闪光": [T(E.DAMAGE)],
    "闪光冲击": [T(E.DAMAGE)],
    "闪击": [T(E.DAMAGE)],
    "闪击折返": [
        T(E.DAMAGE),
        T(E.FORCE_SWITCH),
    ],
    "闪燃": [
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=4.0)),
    ],
    "防反": [T(E.DAMAGE_REDUCTION, pct=0.6)],
    "防御反击": [T(E.DAMAGE_REDUCTION, pct=0.8)],
    "阳火增辉": [T(E.DAMAGE)],
    "降灵": [],
    "除厄": [T(E.DAMAGE)],
    "陨石": [T(E.DAMAGE)],
    "隐藏条款": [],
    "隼鳞": [T(E.DAMAGE)],
    "集中": [T(E.DAMAGE_REDUCTION, pct=0.7)],
    "雪替身": [T(E.DAMAGE_REDUCTION, pct=0.7)],
    "雪球": [T(E.SELF_BUFF, speed=-0.9)],
    "雷暴": [
        T(E.DAMAGE),
        T(E.ENEMY_ENERGY_COST_UP, amount=1),
    ],
    "雾气环绕": [],
    "震击": [T(E.DAMAGE)],
    "霜冻": [T(E.ENEMY_DEBUFF, spdef=1.0)],
    "霜天": [
        T(E.FREEZE, stacks=3),
        T(E.ENEMY_ENERGY_COST_UP, amount=1),
    ],
    "霜降": [T(E.FREEZE, stacks=4)],
    "鞭打": [T(E.DAMAGE)],
    "音波弹": [T(E.DAMAGE)],
    "音爆": [T(E.DAMAGE)],
    "顶端优势": [T(E.DAMAGE)],
    "预备势": [
        T(E.SELF_BUFF, atk=0.8),
        T(E.ENEMY_DEBUFF, {"def": 0.8}),
    ],
    "风吹雪": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "风矢": [T(E.DAMAGE)],
    "风起": [],
    "风隐": [T(E.FORCE_SWITCH)],
    "飞叶": [T(E.DAMAGE)],
    "飞吻": [T(E.DAMAGE)],
    "飞断": [T(E.DAMAGE)],
    "飞羽": [T(E.AGILITY)],
    "飞踢": [T(E.DAMAGE)],
    "食腐": [],
    "骗局": [T(E.DAMAGE)],
    "高温回火": [
        T(E.DAMAGE),
        T(E.FORCE_SWITCH),
    ],
    "鬼火": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "魅惑": [T(E.DAMAGE)],
    "魔法增效": [T(E.SELF_BUFF, spatk=0.7)],
    "魔爪": [
        T(E.DAMAGE),
        T(E.HEAL_ENERGY, amount=1),
    ],
    "魔能爆": [T(E.DAMAGE)],
    "鸣叫": [T(E.DAMAGE)],
    "鸣沙陷阱": [T(E.DAMAGE)],
    "鸩毒": [
        T(E.DAMAGE),
        T(E.POISON, stacks=1),
    ],
    "鹰爪": [T(E.DAMAGE)],
    "麻痹": [T(E.SKILL_MOD, target='enemy', stat='priority', value=-1)],
    "黑手": [T(E.DAMAGE)],
    "鼓劲": [T(E.SELF_BUFF, spdef=1.5)],
    "齿轮切开": [T(E.DAMAGE)],
    "龙之利爪": [
        T(E.DAMAGE),
        T(E.LIFE_DRAIN, pct=0.5),
    ],
    "龙之舞": [],
    "龙卷风": [
        T(E.AGILITY),
        T(E.DAMAGE),
        on_status(T(E.POWER_DYNAMIC, condition='counter', multiplier=5.0)),
    ],
    "龙吟": [T(E.SELF_BUFF, atk=1.0, spatk=1.0)],
    "龙吼": [T(E.DAMAGE)],
    "龙威": [],
    "龙息环爆": [T(E.DAMAGE)],
    "龙炮": [T(E.DAMAGE)],
    "龙爪": [T(E.DAMAGE)],
    "龙血": [T(E.DAMAGE_REDUCTION, pct=0.6)],
}
